using System;
using System.Linq;
namespace VivaLing.Models.Account
{
    public static class MinifyPersonExtensionEx
    {
        private static void MannuallyFrom(this VivaLing.Models.Account.MinifyPersonExtension @this, VivaLing.Models.Account.PersonExtension target)
        {
            // customized mapping
        }

        private static void MannuallyTo(this VivaLing.Models.Account.MinifyPersonExtension @this, VivaLing.Models.Account.PersonExtension target)
        {
            // customized mapping
        }

        public static VivaLing.Models.Account.MinifyPersonExtension ToMinifyPersonExtension(this VivaLing.Models.Account.PersonExtension source)
        {
            return new VivaLing.Models.Account.MinifyPersonExtension().MapFrom(source);
        }

        public static VivaLing.Models.Account.PersonExtension ToPersonExtension(this VivaLing.Models.Account.MinifyPersonExtension derived)
        {
            return derived.MapTo(new VivaLing.Models.Account.PersonExtension());
        }

        public static MinifyPersonExtension MapFrom(this MinifyPersonExtension derived, PersonExtension source)
        {
            // this function is auto-generated by DerivedModel.tt
            // you can add your code in MannuallyFrom
            derived.Id = source.Id;

            derived.MannuallyFrom(source);
            return derived;
        }

        public static PersonExtension MapTo(this MinifyPersonExtension derived, PersonExtension source)
        {
            // this function is auto-generated by DerivedModel.tt
            // you can add your code in MannuallyTo
            source.Id = derived.Id;

            derived.MannuallyTo(source);
            return source;
        }
    }
}
