using System;
using System.Linq;
namespace VivaLing.Models.Account
{
    public static class MinifyAccountEx
    {
        private static void MannuallyFrom(this VivaLing.Models.Account.MinifyAccount @this, VivaLing.Models.Account.Account target)
        {
            // customized mapping
        }

        private static void MannuallyTo(this VivaLing.Models.Account.MinifyAccount @this, VivaLing.Models.Account.Account target)
        {
            // customized mapping
        }

        public static VivaLing.Models.Account.MinifyAccount ToMinifyAccount(this VivaLing.Models.Account.Account source)
        {
            return new VivaLing.Models.Account.MinifyAccount().MapFrom(source);
        }

        public static VivaLing.Models.Account.Account ToAccount(this VivaLing.Models.Account.MinifyAccount derived)
        {
            return derived.MapTo(new VivaLing.Models.Account.Account());
        }

        public static MinifyAccount MapFrom(this MinifyAccount derived, Account source)
        {
            // this function is auto-generated by DerivedModel.tt
            // you can add your code in MannuallyFrom
            derived.Id = source.Id;
            derived.Name = source.Name;

            derived.MannuallyFrom(source);
            return derived;
        }

        public static Account MapTo(this MinifyAccount derived, Account source)
        {
            // this function is auto-generated by DerivedModel.tt
            // you can add your code in MannuallyTo
            source.Id = derived.Id;
            source.Name = derived.Name;

            derived.MannuallyTo(source);
            return source;
        }
    }
}
